# Generated by Django 5.0.7 on 2026-03-14 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('authentication', '0001_initial'),
        ('campuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='systemmetric',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='campuses.campus'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_a_user_id_7c722c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='analytics_a_model_n_cbae55_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='analytics_a_action_c1a4bb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='analytics_a_timesta_184ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetric',
            index=models.Index(fields=['metric_name', 'recorded_at'], name='analytics_s_metric__8b20e8_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetric',
            index=models.Index(fields=['campus', 'metric_name'], name='analytics_s_campus__dcf5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetric',
            index=models.Index(fields=['recorded_at'], name='analytics_s_recorde_8d8b9e_idx'),
        ),
    ]
