# Generated by Django 5.0.7 on 2026-03-14 21:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('campuses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('staff_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract')], db_index=True, default='FULL_TIME', max_length=20)),
                ('hire_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('qualifications', models.TextField(help_text='Academic qualifications and certifications')),
                ('specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('office_location', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], db_index=True, default='ACTIVE', max_length=20)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='campuses.campus')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='campuses.department')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'LECTURER'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='authentication.user')),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['-hire_date', 'staff_id'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('ON_LEAVE', 'On Leave')], db_index=True, default='PRESENT', max_length=20)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='staff.staffmember')),
            ],
            options={
                'verbose_name': 'Staff Attendance',
                'verbose_name_plural': 'Staff Attendances',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['staff_id'], name='staff_staff_staff_i_d27e17_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['campus', 'status'], name='staff_staff_campus__479ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['department'], name='staff_staff_departm_067751_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['employment_type'], name='staff_staff_employm_89dc70_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['status'], name='staff_staff_status_28b777_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['staff', 'date'], name='staff_staff_staff_i_9c87ac_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['date'], name='staff_staff_date_5bf703_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['status'], name='staff_staff_status_e16c6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffattendance',
            unique_together={('staff', 'date')},
        ),
    ]
