# Generated by Django 5.0.3 on 2026-04-04 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, help_text='Unique code like VIEW_GRADES, SUBMIT_ASSIGNMENT', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable name', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('FINANCE', 'Finance'), ('ADMIN', 'Administration'), ('STUDENT_SERVICES', 'Student Services'), ('REGISTRY', 'Registry'), ('HR', 'Human Resources'), ('LIBRARY', 'Library'), ('EXAMS', 'Examinations')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_campus', models.BooleanField(default=False, help_text='If True, user must have a campus assigned')),
                ('requires_approval', models.BooleanField(default=False, help_text='If True, action requires approval from higher authority')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'rbac_permissions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('CAMPUS_ADMIN', 'Campus Admin'), ('CHANCELLOR', 'Chancellor'), ('DEAN', 'Dean'), ('HEAD_OF_DEPARTMENT', 'Head of Department'), ('LECTURER', 'Lecturer'), ('PART_TIME_LECTURER', 'Part-Time Lecturer'), ('FACULTY_ADMIN', 'Faculty Admin'), ('FACULTY_EXAM', 'Faculty Exam'), ('REGISTRY_ADMIN', 'Registry Admin'), ('REGISTRY', 'Registry'), ('REGISTRY_ADMISSION', 'Registry Admission'), ('REGISTRY_HR', 'Registry HR'), ('REGISTRY_ACADEMIC', 'Registry Academic'), ('FINANCE', 'Finance'), ('FINANCE_STAFF', 'Finance Staff'), ('FINANCE_SECRETARIAT', 'Finance Secretariat'), ('FINANCE_SECRETARIAT_STAFF', 'Finance Secretariat Staff'), ('ACCOUNTANT', 'Accountant'), ('STUDENT_SECTION', 'Student Section'), ('STUDENT_SECTION_STAFF', 'Student Section Staff'), ('STUDENT_WARDEN', 'Student Warden'), ('BUSINESS_CENTER', 'Business Center'), ('CAMPUS_BUSINESS_CENTER', 'Campus Business Center'), ('LIBRARY', 'Library'), ('ID_CARD_PRINTING', 'ID Card Printing'), ('HELP_DESK', 'Help Desk'), ('HUMAN_RESOURCES', 'Human Resources'), ('ELEARNING_ADMIN', 'eLearning Admin'), ('SPS_ADMIN', 'SPS Admin'), ('SPS_STAFF', 'SPS Staff'), ('EXTRAMURAL_STUDIES', 'Extramural Studies'), ('EXAMS', 'Exams'), ('STUDENT', 'Student'), ('PARENT', 'Parent')], db_index=True, default='STUDENT', max_length=50),
        ),
        migrations.CreateModel(
            name='RoleHierarchy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parent_role', models.CharField(db_index=True, help_text='Parent role that grants permissions', max_length=50)),
                ('child_role', models.CharField(db_index=True, help_text='Child role that inherits permissions', max_length=50)),
                ('inherit_all', models.BooleanField(default=True, help_text='If True, inherit ALL parent permissions')),
            ],
            options={
                'verbose_name': 'Role Hierarchy',
                'verbose_name_plural': 'Role Hierarchies',
                'db_table': 'rbac_role_hierarchy',
                'unique_together': {('parent_role', 'child_role')},
            },
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('ROLE_PERM_GRANT', 'Role Permission Granted'), ('ROLE_PERM_REVOKE', 'Role Permission Revoked'), ('USER_PERM_GRANT', 'User Permission Granted'), ('USER_PERM_REVOKE', 'User Permission Revoked'), ('PERM_CREATED', 'Permission Created'), ('PERM_MODIFIED', 'Permission Modified'), ('PERM_DELETED', 'Permission Deleted')], max_length=50)),
                ('affected_role', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('old_value', models.JSONField(blank=True, help_text='State before change', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='State after change', null=True)),
                ('affected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_changes', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_actions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.permission')),
            ],
            options={
                'verbose_name': 'Permission Audit Log',
                'verbose_name_plural': 'Permission Audit Logs',
                'db_table': 'rbac_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='rbac_audit__created_2ecaef_idx'), models.Index(fields=['performed_by', '-created_at'], name='rbac_audit__perform_915ef1_idx'), models.Index(fields=['affected_user', '-created_at'], name='rbac_audit__affecte_db650a_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(db_index=True, help_text='Role name (STUDENT, LECTURER, etc.)', max_length=50)),
                ('is_inherited', models.BooleanField(default=False, help_text='If True, this permission is inherited from parent role')),
                ('can_delegate', models.BooleanField(default=False, help_text='If True, users with this role can delegate this permission')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_role_permissions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='authentication.permission')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'rbac_role_permissions',
                'ordering': ['role', 'permission'],
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('GRANT', 'Grant Permission'), ('REVOKE', 'Revoke Permission')], help_text='GRANT = add permission, REVOKE = remove permission', max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Reason for granting/revoking this permission', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='If set, permission expires at this time', null=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_user_permissions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='authentication.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'db_table': 'rbac_user_permissions',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
