# Generated by Django 5.0.7 on 2026-04-04 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_permission_alter_user_role_rolehierarchy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('permission_required', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('escalation_hours', models.IntegerField(default=48, help_text='Hours before auto-escalation to next approver')),
                ('notify_on_submission', models.BooleanField(default=True)),
                ('notify_on_approval', models.BooleanField(default=True)),
                ('notify_on_rejection', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Approval Chain',
                'verbose_name_plural': 'Approval Chains',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('request_data', models.JSONField(blank=True, help_text='Additional data related to the request', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('current_level', models.IntegerField(default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-reject after this date', null=True)),
                ('final_decision_at', models.DateTimeField(blank=True, null=True)),
                ('final_decision_notes', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, help_text='List of file URLs or document IDs', null=True)),
                ('approval_chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='authentication.approvalchain')),
                ('final_decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal comments only visible to approvers')),
                ('mentioned_users', models.ManyToManyField(blank=True, related_name='approval_mentions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_comments', to=settings.AUTH_USER_MODEL)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='authentication.approvalrequest')),
            ],
            options={
                'verbose_name': 'Approval Comment',
                'verbose_name_plural': 'Approval Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('level_number', models.IntegerField()),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMMENTED', 'Commented'), ('REQUESTED_INFO', 'Requested More Information'), ('CANCELLED', 'Cancelled'), ('ESCALATED', 'Auto-Escalated')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='authentication.approvalrequest')),
            ],
            options={
                'verbose_name': 'Approval Action',
                'verbose_name_plural': 'Approval Actions',
                'ordering': ['-acted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('title_template', models.CharField(help_text='Template with placeholders like {student_name}, {course_code}', max_length=255)),
                ('description_template', models.TextField()),
                ('form_schema', models.JSONField(help_text='JSON schema defining required fields for this template')),
                ('is_active', models.BooleanField(default=True)),
                ('approval_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='authentication.approvalchain')),
            ],
            options={
                'verbose_name': 'Approval Template',
                'verbose_name_plural': 'Approval Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('level_number', models.IntegerField()),
                ('role', models.CharField(help_text='Role required to approve at this level', max_length=50)),
                ('require_all_approvers', models.BooleanField(default=False, help_text='If true, all specific_approvers must approve. Otherwise, any one can approve.')),
                ('can_skip', models.BooleanField(default=False, help_text='Can this level be skipped if approver is unavailable?')),
                ('approval_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='authentication.approvalchain')),
                ('specific_approvers', models.ManyToManyField(blank=True, related_name='approval_levels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Level',
                'verbose_name_plural': 'Approval Levels',
                'ordering': ['approval_chain', 'level_number'],
                'unique_together': {('approval_chain', 'level_number')},
            },
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'current_level'], name='authenticat_status_c0c118_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['submitted_by', 'status'], name='authenticat_submitt_076587_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['approval_chain', 'status'], name='authenticat_approva_5ff2f9_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['approval_request', 'level_number'], name='authenticat_approva_25673b_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['approver', 'action'], name='authenticat_approve_95fff1_idx'),
        ),
    ]
