# Generated by Django 5.0.7 on 2026-04-05 12:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_approvalchain_approvalrequest_approvalcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('session_token', models.CharField(db_index=True, help_text='JWT token or session ID', max_length=500, unique=True)),
                ('refresh_token', models.CharField(blank=True, help_text='JWT refresh token', max_length=500, null=True)),
                ('device_type', models.CharField(blank=True, help_text='Mobile, Desktop, Tablet', max_length=50, null=True)),
                ('device_name', models.CharField(blank=True, help_text='Device model or name', max_length=200, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('login_method', models.CharField(choices=[('PASSWORD', 'Password'), ('2FA', 'Two-Factor Authentication'), ('SSO', 'Single Sign-On'), ('SOCIAL', 'Social Login')], default='PASSWORD', max_length=50)),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('is_suspicious', models.BooleanField(default=False, help_text='Flagged for suspicious activity')),
                ('force_logout', models.BooleanField(default=False, help_text='Admin can force logout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='SessionActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('activity_type', models.CharField(choices=[('PAGE_VIEW', 'Page View'), ('API_CALL', 'API Call'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('PERMISSION_CHANGE', 'Permission Change'), ('PROFILE_UPDATE', 'Profile Update'), ('DATA_EXPORT', 'Data Export'), ('SUSPICIOUS', 'Suspicious Activity')], max_length=50)),
                ('activity_description', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('http_method', models.CharField(blank=True, max_length=10, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='authentication.usersession')),
            ],
            options={
                'verbose_name': 'Session Activity',
                'verbose_name_plural': 'Session Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fingerprint_hash', models.CharField(db_index=True, help_text='SHA256 hash of device characteristics', max_length=64, unique=True)),
                ('fingerprint_data', models.JSONField(help_text='Device characteristics used for fingerprinting')),
                ('device_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_trusted', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('login_count', models.IntegerField(default=0)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_fingerprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Fingerprint',
                'verbose_name_plural': 'Device Fingerprints',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'is_trusted'], name='authenticat_user_id_23df6e_idx'), models.Index(fields=['fingerprint_hash'], name='authenticat_fingerp_51374f_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('failure_reason', models.CharField(blank=True, choices=[('INVALID_PASSWORD', 'Invalid Password'), ('USER_NOT_FOUND', 'User Not Found'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_INACTIVE', 'Account Inactive'), ('2FA_REQUIRED', '2FA Required'), ('2FA_FAILED', '2FA Failed'), ('IP_BLOCKED', 'IP Blocked')], max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'success'], name='authenticat_email_6be2db_idx'), models.Index(fields=['ip_address', 'created_at'], name='authenticat_ip_addr_1dccaa_idx'), models.Index(fields=['user', 'created_at'], name='authenticat_user_id_8191e7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='authenticat_user_id_f427c8_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_token'], name='authenticat_session_30c7e0_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['ip_address', 'user'], name='authenticat_ip_addr_d62146_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_8c23d2_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionactivity',
            index=models.Index(fields=['session', 'created_at'], name='authenticat_session_705b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionactivity',
            index=models.Index(fields=['activity_type', 'created_at'], name='authenticat_activit_8880b8_idx'),
        ),
    ]
