# Generated by Django 5.0.7 on 2026-03-14 21:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuses', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('credits', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
                ('syllabus', models.TextField(blank=True, null=True)),
                ('is_elective', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='campuses.campus')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='campuses.department')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_for', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('semester', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=9)),
                ('schedule', models.JSONField(default=dict, help_text="Days and times as JSON (e.g., {'Monday': '10:00-12:00', 'Wednesday': '10:00-12:00'})")),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('max_students', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('enrolled_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='OPEN', max_length=20)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='campuses.campus')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='courses.course')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to='staff.staffmember')),
            ],
            options={
                'verbose_name': 'Course Offering',
                'verbose_name_plural': 'Course Offerings',
                'ordering': ['-academic_year', 'semester', 'course__code'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('degree_type', models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'PhD'), ('DIPLOMA', 'Diploma'), ('CERTIFICATE', 'Certificate')], db_index=True, max_length=20)),
                ('duration_years', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_credits', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='campuses.campus')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='campuses.department')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['campus', 'degree_type', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='courses_cou_code_612388_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['campus', 'department'], name='courses_cou_campus__c46241_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='courses_cou_is_acti_3c7e41_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_elective'], name='courses_cou_is_elec_432ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['course', 'semester'], name='courses_cou_course__90fffb_idx'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['academic_year'], name='courses_cou_academi_d470c8_idx'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['campus', 'status'], name='courses_cou_campus__39d7ce_idx'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['instructor'], name='courses_cou_instruc_ae28e7_idx'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['status'], name='courses_cou_status_2ba5d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('course', 'semester', 'academic_year', 'campus')},
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['code'], name='courses_pro_code_900595_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['campus', 'department'], name='courses_pro_campus__e71628_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['degree_type'], name='courses_pro_degree__210650_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['is_active'], name='courses_pro_is_acti_eb7f6a_idx'),
        ),
    ]
