# RabbitMQ Production Configuration
# Network & Protocol
vm_memory_high_watermark.relative = 0.6
vm_memory_high_watermark_paging_ratio = 0.75

# Message TTL
max_message_size = 134217728

# Logging
log.file.level = warning
log.console = true
log.console.level = warning
