# Generated by Django 5.0.7 on 2026-04-04 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuses', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0002_courseregistration_leaveapplication_studentdocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('signature_image', models.ImageField(help_text='Upload signature image', upload_to='letters/signatures/')),
                ('title', models.CharField(help_text='e.g., Vice Chancellor, Registrar, Dean', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='campuses.campus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Letter Signature',
                'verbose_name_plural': 'Letter Signatures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('letter_type', models.CharField(choices=[('ADMISSION', 'Admission Letter'), ('OFFER', 'Offer Letter'), ('REFERENCE', 'Reference Letter'), ('TRANSCRIPT', 'Transcript Request'), ('PROVISIONAL', 'Provisional Admission'), ('CONFIRMATION', 'Confirmation of Studies'), ('RECOMMENDATION', 'Recommendation Letter'), ('WITHDRAWAL', 'Withdrawal Confirmation'), ('SUSPENSION', 'Suspension Notice'), ('EXPULSION', 'Expulsion Notice'), ('COMPLETION', 'Course Completion'), ('INTERNSHIP', 'Internship Letter'), ('EMPLOYMENT', 'Employment Verification'), ('CUSTOM', 'Custom Letter')], max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField(help_text='Use {{variable}} for dynamic content')),
                ('header_html', models.TextField(blank=True, help_text='HTML for letter header', null=True)),
                ('footer_html', models.TextField(blank=True, help_text='HTML for letter footer', null=True)),
                ('requires_signature', models.BooleanField(default=True)),
                ('signature_roles', models.JSONField(default=list, help_text='List of roles that can sign this letter type')),
                ('is_active', models.BooleanField(default=True)),
                ('available_variables', models.JSONField(default=dict, help_text='Dictionary of variables that can be used in this template')),
                ('campus', models.ForeignKey(blank=True, help_text='Campus-specific template, null for system-wide', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_templates', to='campuses.campus')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_letter_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Letter Template',
                'verbose_name_plural': 'Letter Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_name', models.CharField(help_text='Fallback if not student/staff', max_length=255)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(max_length=500)),
                ('content', models.TextField(help_text='Rendered letter content with variables replaced')),
                ('rendered_html', models.TextField(help_text='Full HTML of the letter')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_SIGNATURE', 'Pending Signature'), ('SIGNED', 'Signed'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=50)),
                ('reference_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('digital_signature', models.TextField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='letters/pdfs/')),
                ('metadata', models.JSONField(default=dict, help_text='Additional data used in letter generation')),
                ('notes', models.TextField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='campuses.campus')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_letters', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_letters', to=settings.AUTH_USER_MODEL)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_letters', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='staff.staffmember')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='students.student')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_letters', to='letters.lettertemplate')),
            ],
            options={
                'verbose_name': 'Generated Letter',
                'verbose_name_plural': 'Generated Letters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LetterLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SIGNED', 'Signed'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled'), ('DOWNLOADED', 'Downloaded'), ('EMAILED', 'Emailed'), ('VIEWED', 'Viewed')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='letters.generatedletter')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Letter Log',
                'verbose_name_plural': 'Letter Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['letter', 'action'], name='letters_let_letter__669111_idx'), models.Index(fields=['created_at'], name='letters_let_created_ca3b9d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lettertemplate',
            index=models.Index(fields=['letter_type', 'is_active'], name='letters_let_letter__5b505b_idx'),
        ),
        migrations.AddIndex(
            model_name='lettertemplate',
            index=models.Index(fields=['campus', 'letter_type'], name='letters_let_campus__624677_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedletter',
            index=models.Index(fields=['reference_number'], name='letters_gen_referen_a7f84d_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedletter',
            index=models.Index(fields=['status', 'campus'], name='letters_gen_status_7787d0_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedletter',
            index=models.Index(fields=['student', 'status'], name='letters_gen_student_f4f0a5_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedletter',
            index=models.Index(fields=['created_at'], name='letters_gen_created_0480b9_idx'),
        ),
    ]
