# Generated by Django 5.0.7 on 2026-03-14 21:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Campus-specific settings and configurations')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuses',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='campuses_ca_code_3634e9_idx'), models.Index(fields=['is_active'], name='campuses_ca_is_acti_66e6bb_idx'), models.Index(fields=['city'], name='campuses_ca_city_4f98e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='campuses.campus')),
                ('head', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['LECTURER', 'DEAN', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='authentication.user')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['campus', 'name'],
                'indexes': [models.Index(fields=['campus', 'code'], name='campuses_de_campus__bb1602_idx'), models.Index(fields=['is_active'], name='campuses_de_is_acti_2b6558_idx'), models.Index(fields=['head'], name='campuses_de_head_id_fc3fdd_idx')],
                'unique_together': {('campus', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='campuses.campus')),
                ('dean', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['DEAN', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deanships', to='authentication.user')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'ordering': ['campus', 'name'],
                'indexes': [models.Index(fields=['campus', 'code'], name='campuses_fa_campus__57dee5_idx'), models.Index(fields=['dean'], name='campuses_fa_dean_id_fee1c9_idx')],
                'unique_together': {('campus', 'code')},
            },
        ),
    ]
