# Generated by Django 5.0.7 on 2026-04-04 19:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('batch_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('pin_type', models.CharField(choices=[('APPLICATION', 'Application Form'), ('ADMISSION', 'Admission Processing'), ('TRANSCRIPT', 'Transcript Request'), ('VERIFICATION', 'Document Verification'), ('PORTAL_ACCESS', 'Portal Access'), ('CUSTOM', 'Custom')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('price_per_pin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEPLETED', 'Depleted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=50)),
                ('used_count', models.IntegerField(default=0)),
                ('remaining_count', models.IntegerField()),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin_batches', to='campuses.campus')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pin_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pin Batch',
                'verbose_name_plural': 'Pin Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pin_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('serial_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('UNUSED', 'Unused'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='UNUSED', max_length=50)),
                ('used_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('used_by_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('valid_until', models.DateTimeField()),
                ('metadata', models.JSONField(default=dict, help_text='Additional data from pin usage')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_pins', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='business_center.pinbatch')),
            ],
            options={
                'verbose_name': 'Application Pin',
                'verbose_name_plural': 'Application Pins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PinVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('verified_by_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('verification_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('was_successful', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='business_center.applicationpin')),
            ],
            options={
                'verbose_name': 'Pin Verification',
                'verbose_name_plural': 'Pin Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('receipt_type', models.CharField(choices=[('PIN_PURCHASE', 'Pin Purchase'), ('FEE_PAYMENT', 'Fee Payment'), ('APPLICATION_FEE', 'Application Fee'), ('SERVICE_CHARGE', 'Service Charge'), ('VERIFICATION_FEE', 'Verification Fee'), ('CUSTOM', 'Custom Receipt')], max_length=50)),
                ('payer_name', models.CharField(max_length=255)),
                ('payer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('ONLINE', 'Online Payment')], max_length=50)),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='campuses.campus')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_receipts', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_receipts', to=settings.AUTH_USER_MODEL)),
                ('payer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to=settings.AUTH_USER_MODEL)),
                ('pin_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='business_center.pinbatch')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('DAILY', 'Daily Report'), ('WEEKLY', 'Weekly Report'), ('MONTHLY', 'Monthly Report'), ('QUARTERLY', 'Quarterly Report'), ('YEARLY', 'Yearly Report')], max_length=50)),
                ('report_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_pins_sold', models.IntegerField(default=0)),
                ('total_pins_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_receipts_issued', models.IntegerField(default=0)),
                ('total_receipts_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sales_by_type', models.JSONField(default=dict)),
                ('sales_by_method', models.JSONField(default=dict)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='business_center/reports/')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_reports', to='campuses.campus')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_sales_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Report',
                'verbose_name_plural': 'Sales Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.AddIndex(
            model_name='pinbatch',
            index=models.Index(fields=['batch_number'], name='business_ce_batch_n_f3c7ba_idx'),
        ),
        migrations.AddIndex(
            model_name='pinbatch',
            index=models.Index(fields=['status', 'pin_type'], name='business_ce_status_345036_idx'),
        ),
        migrations.AddIndex(
            model_name='pinbatch',
            index=models.Index(fields=['campus', 'status'], name='business_ce_campus__203bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationpin',
            index=models.Index(fields=['pin_number'], name='business_ce_pin_num_be3b24_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationpin',
            index=models.Index(fields=['serial_number'], name='business_ce_serial__a76101_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationpin',
            index=models.Index(fields=['status', 'batch'], name='business_ce_status_60e9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationpin',
            index=models.Index(fields=['used_by'], name='business_ce_used_by_8a8938_idx'),
        ),
        migrations.AddIndex(
            model_name='pinverification',
            index=models.Index(fields=['pin', 'created_at'], name='business_ce_pin_id_6fcf64_idx'),
        ),
        migrations.AddIndex(
            model_name='pinverification',
            index=models.Index(fields=['verification_ip'], name='business_ce_verific_51ebe4_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='business_ce_receipt_1f6b69_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_type', 'campus'], name='business_ce_receipt_b4d383_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['payer_user'], name='business_ce_payer_u_04738f_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['payment_date'], name='business_ce_payment_d3698e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreport',
            index=models.Index(fields=['report_date', 'campus'], name='business_ce_report__8b2c75_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreport',
            index=models.Index(fields=['report_type', 'campus'], name='business_ce_report__c0b15a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesreport',
            unique_together={('report_type', 'report_date', 'campus')},
        ),
    ]
